[package]
name = "esp8266-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp8266-hal = { version = "0.5.1" }
panic-halt = { version = "0.2.0" }

[profile.release]
lto = true
